
package fr.afcepf.atod.webservice.image;

import java.util.Map;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IServiceImage", targetNamespace = "http://images.wine.al30.afcepf.fr")
public interface IServiceImage {


    /**
     * 
     * @param imageURL
     * @return
     *     returns fr.afcepf.al30.wine.images.DownloadImagesResponse.ResultImages64
     * @throws WineServerUtilException_Exception
     */
    @WebMethod
    @WebResult(name = "resultImages64", targetNamespace = "")
    @RequestWrapper(localName = "downloadImages", targetNamespace = "http://images.wine.al30.afcepf.fr", className = "fr.afcepf.al30.wine.images.DownloadImages")
    @ResponseWrapper(localName = "downloadImagesResponse", targetNamespace = "http://images.wine.al30.afcepf.fr", className = "fr.afcepf.al30.wine.images.DownloadImagesResponse")
    public Map<String,String> downloadImages(
        @WebParam(name = "imageURL", targetNamespace = "")
        String imageURL)
        throws WineServerUtilException_Exception
    ;

    /**
     * 
     * @param encodeImage
     * @param name
     * @return
     *     returns java.lang.String
     * @throws WineServerUtilException_Exception
     */
    @WebMethod
    @WebResult(name = "uploadImages", targetNamespace = "")
    @RequestWrapper(localName = "uploadImages", targetNamespace = "http://images.wine.al30.afcepf.fr", className = "fr.afcepf.al30.wine.images.UploadImages")
    @ResponseWrapper(localName = "uploadImagesResponse", targetNamespace = "http://images.wine.al30.afcepf.fr", className = "fr.afcepf.al30.wine.images.UploadImagesResponse")
    public String uploadImages(
        @WebParam(name = "encodeImage", targetNamespace = "")
        String encodeImage,
        @WebParam(name = "name", targetNamespace = "")
        String name)
        throws WineServerUtilException_Exception
    ;

}
